In [1]:
import os
import glob
import re
import numpy as np
import pandas as pd
import rasterio

In [2]:
raster_folder = "/Users/cherryleheu/Documents/HCDP/climate_report/dependencies/rainfall"

records = []

for tif in sorted(glob.glob(os.path.join(raster_folder, "rainfall_*_06.tif"))):
    year = int(re.search(r"rainfall_(\d{4})_06\.tif", os.path.basename(tif)).group(1))

    with rasterio.open(tif) as src:
        arr = src.read(1, masked=True)

    mean_mm = arr.mean()
    mean_in = mean_mm / 25.4

    records.append({
        "year": year,
        "mean_rainfall_in": float(mean_in),
    })

df = pd.DataFrame(records).sort_values("year").reset_index(drop=True)
df

     year  mean_rainfall_in
0    1920          2.730493
1    1921          1.750963
2    1922          1.566024
3    1923          3.226786
4    1924          2.407401
..    ...               ...
102  2022          3.438154
103  2023          3.089550
104  2024          2.622625
105  2025          3.358494
106  2026          7.027416

[107 rows x 2 columns]

In [3]:
# rank 1 = wettest June (highest statewide total rainfall)
df["rank"] = df["mean_rainfall_in"].rank(method="min", ascending=False).astype(int)
df = df.sort_values("rank").reset_index(drop=True)
df

     year  mean_rainfall_in  rank
0    1997          9.209509     1
1    1934          7.162437     2
2    2026          7.027416     3
3    1941          6.876218     4
4    1978          6.429622     5
..    ...               ...   ...
102  1921          1.750963   103
103  1985          1.740035   104
104  1981          1.731060   105
105  1922          1.566024   106
106  1959          1.511918   107

[107 rows x 3 columns]

In [4]:
current_year = df.loc[df["year"] == 2026]
current_year

   year  mean_rainfall_in  rank
2  2026          7.027416     3