In [1]:
import os
import re
import glob
import argparse
import requests
import pandas as pd
import numpy as np
import geopandas as gpd
import rasterio
from urllib.parse import urlencode
from datetime import datetime
from rasterstats import zonal_stats

In [2]:
def convert_units(value, dataset):
    """Convert rainfall mm→inches and temperature °C→°F."""
    if value is None or np.isnan(value):
        return np.nan
    if dataset == "rainfall":
        return value / 25.4  # mm → inches
    elif dataset == "temperature":
        return (value * 9/5) + 32  # °C → °F
    return value

In [3]:
tif_path = "/Users/cherryleheu/Documents/HCDP/Data/annual_rf_all"


# # --- Load climatology ---
# with rasterio.open(climo_file) as src:
#     clim = src.read(1).astype(float)
#     clim = np.where(src.nodata == src.read(1), np.nan, clim)
#     climo_mean = convert_units(np.nanmean(clim), dataset)

#     # --- Loop through all historical rasters to get mean and anomaly ---
all_records = []
for tif in sorted(glob.glob(os.path.join(tif_path, f"*.tif"))):
    parts = os.path.basename(tif).replace(".tif", "").split("_")
    year = parts[1]
    date = f"{year}"

    with rasterio.open(tif) as src:
        arr = src.read(1).astype(float)
        arr = np.where(arr == src.nodata, np.nan, arr)
        mean_val = np.nanmean(arr)

    all_records.append({
        "date": date,
        "year": int(year),
        "mean": mean_val
    })

df = pd.DataFrame(all_records)

df["rank"] = df["mean"].rank(method="min", ascending=True)

df

     date  year         mean   rank
0    1920  1920  1546.811332   33.0
1    1921  1921  1904.286918   75.0
2    1922  1922  1799.935181   68.0
3    1923  1923  2512.253361  105.0
4    1924  1924  1638.628186   47.0
..    ...   ...          ...    ...
101  2021  2021  1778.105613   63.0
102  2022  2022  1128.450986    4.0
103  2023  2023  1589.244796   41.0
104  2024  2024  1419.567413   20.0
105  2025  2025  1066.688672    2.0

[106 rows x 4 columns]

In [7]:
#Tmean
tif_path = "/Users/cherryleheu/Documents/HCDP/Data/annual/tmean/calendar_year"

all_records = []
for tif in sorted(glob.glob(os.path.join(tif_path, f"*_agg.tif"))):
    parts = os.path.basename(tif).replace(".tif", "").split("_")
    year = parts[2]
    date = f"{year}"

    with rasterio.open(tif) as src:
        arr = src.read(1).astype(float)
        arr = np.where(arr == src.nodata, np.nan, arr)
        mean_val = np.nanmean(arr)

    all_records.append({
        "date": date,
        "year": int(year),
        "mean": mean_val*9/5 + 32  
    })

df = pd.DataFrame(all_records)

df["rank"] = df["mean"].rank(method="min", ascending=False)

df

    date  year       mean  rank
0   1990  1990  65.801174  28.0
1   1991  1991  65.641067  32.0
2   1992  1992  65.888010  27.0
3   1993  1993  65.107939  35.0
4   1994  1994  65.549973  33.0
5   1995  1995  66.172545  22.0
6   1996  1996  66.240123  20.0
7   1997  1997  65.703645  30.0
8   1998  1998  65.045232  36.0
9   1999  1999  65.273941  34.0
10  2000  2000  66.190035  21.0
11  2001  2001  66.472786  16.0
12  2002  2002  66.633570  15.0
13  2003  2003  66.883515   9.0
14  2004  2004  67.073190   5.0
15  2005  2005  66.757676  13.0
16  2006  2006  66.453050  17.0
17  2007  2007  66.152690  23.0
18  2008  2008  65.673848  31.0
19  2009  2009  66.001974  26.0
20  2010  2010  66.034843  25.0
21  2011  2011  66.040327  24.0
22  2012  2012  65.781013  29.0
23  2013  2013  66.314509  18.0
24  2014  2014  66.959274   8.0
25  2015  2015  67.285556   3.0
26  2016  2016  66.832407  10.0
27  2017  2017  66.693436  14.0
28  2018  2018  67.080727   4.0
29  2019  2019  67.587765   1.0
30  2020  2020  67.285994   2.0
31  2021  2021  66.299837  19.0
32  2022  2022  66.960647   7.0
33  2023  2023  66.799028  11.0
34  2024  2024  66.763835  12.0
35  2025  2025  67.058604   6.0

In [8]:
#Tmin
tif_path = "/Users/cherryleheu/Documents/HCDP/Data/annual/tmin/calendar_year"

all_records = []
for tif in sorted(glob.glob(os.path.join(tif_path, f"*_agg.tif"))):
    parts = os.path.basename(tif).replace(".tif", "").split("_")
    year = parts[2]
    date = f"{year}"

    with rasterio.open(tif) as src:
        arr = src.read(1).astype(float)
        arr = np.where(arr == src.nodata, np.nan, arr)
        mean_val = np.nanmean(arr)

    all_records.append({
        "date": date,
        "year": int(year),
        "mean": mean_val*9/5 + 32
    })

df = pd.DataFrame(all_records)

df["rank"] = df["mean"].rank(method="min", ascending=False)

df

    date  year       mean  rank
0   1990  1990  58.256866  29.0
1   1991  1991  57.645122  35.0
2   1992  1992  58.279095  28.0
3   1993  1993  57.592039  36.0
4   1994  1994  58.533491  23.0
5   1995  1995  58.372302  26.0
6   1996  1996  59.096838  14.0
7   1997  1997  58.538588  22.0
8   1998  1998  57.696056  33.0
9   1999  1999  57.660617  34.0
10  2000  2000  58.346035  27.0
11  2001  2001  58.852090  16.0
12  2002  2002  58.764084  18.0
13  2003  2003  58.782502  17.0
14  2004  2004  59.379150  10.0
15  2005  2005  58.862006  15.0
16  2006  2006  58.726418  19.0
17  2007  2007  58.571758  21.0
18  2008  2008  58.148548  32.0
19  2009  2009  58.532968  24.0
20  2010  2010  58.219098  30.0
21  2011  2011  58.461968  25.0
22  2012  2012  58.158258  31.0
23  2013  2013  58.707821  20.0
24  2014  2014  59.388115   9.0
25  2015  2015  59.761243   5.0
26  2016  2016  59.571236   7.0
27  2017  2017  59.241759  12.0
28  2018  2018  60.225037   2.0
29  2019  2019  60.230447   1.0
30  2020  2020  60.037570   3.0
31  2021  2021  59.133369  13.0
32  2022  2022  59.346909  11.0
33  2023  2023  59.522210   8.0
34  2024  2024  59.612713   6.0
35  2025  2025  59.879924   4.0

In [9]:
#Tmax
tif_path = "/Users/cherryleheu/Documents/HCDP/Data/annual/tmax/calendar_year"

all_records = []
for tif in sorted(glob.glob(os.path.join(tif_path, f"*_agg.tif"))):
    parts = os.path.basename(tif).replace(".tif", "").split("_")
    year = parts[2]
    date = f"{year}"

    with rasterio.open(tif) as src:
        arr = src.read(1).astype(float)
        arr = np.where(arr == src.nodata, np.nan, arr)
        mean_val = np.nanmean(arr)

    all_records.append({
        "date": date,
        "year": int(year),
        "mean": mean_val*9/5 + 32
    })

df = pd.DataFrame(all_records)

df["rank"] = df["mean"].rank(method="min", ascending=False)

df

    date  year       mean  rank
0   1990  1990  73.345689  30.0
1   1991  1991  73.637233  23.0
2   1992  1992  73.497341  25.0
3   1993  1993  72.623943  34.0
4   1994  1994  72.566764  35.0
5   1995  1995  73.973006  17.0
6   1996  1996  73.383554  29.0
7   1997  1997  72.869085  33.0
8   1998  1998  72.394630  36.0
9   1999  1999  72.887622  32.0
10  2000  2000  74.034663  16.0
11  2001  2001  74.093824  14.0
12  2002  2002  74.503569   9.0
13  2003  2003  74.984692   1.0
14  2004  2004  74.767577   4.0
15  2005  2005  74.654028   5.0
16  2006  2006  74.179863  11.0
17  2007  2007  73.733756  22.0
18  2008  2008  73.199510  31.0
19  2009  2009  73.471185  26.0
20  2010  2010  73.850945  21.0
21  2011  2011  73.617493  24.0
22  2012  2012  73.404275  28.0
23  2013  2013  73.921404  19.0
24  2014  2014  74.530522   8.0
25  2015  2015  74.810121   3.0
26  2016  2016  74.094794  13.0
27  2017  2017  74.145214  12.0
28  2018  2018  73.936587  18.0
29  2019  2019  74.945378   2.0
30  2020  2020  74.534816   7.0
31  2021  2021  73.466581  27.0
32  2022  2022  74.574733   6.0
33  2023  2023  74.076192  15.0
34  2024  2024  73.915288  20.0
35  2025  2025  74.244645  10.0